
-- 1) Fix wrong images on existing rows
UPDATE public.meals
SET image_url = 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=1200&q=80'
WHERE name = 'Classic French Omelette';

-- 2) Seed dish-matched recipes for each meal_time so every slot has >=20 cards
INSERT INTO public.meals (source, source_id, name, cuisine, image_url, description, ingredients, instructions, tools, prep_minutes, calories, tags, health_flags, meal_time, is_alcohol, affordability)
VALUES
-- ============ BREAKFAST (need ~16 more to reach 20) ============
('seed','bf-001','Greek Yogurt Parfait','Mediterranean','https://images.unsplash.com/photo-1488477181946-6428a0291777?w=1200&q=80','Yogurt layered with granola and fresh berries.','[{"name":"Greek yogurt"},{"name":"granola"},{"name":"berries"},{"name":"honey"}]'::jsonb,'Layer yogurt, granola, and berries; drizzle honey.',ARRAY['bowl','spoon'],5,320,ARRAY['high-protein','vegetarian'],ARRAY['gluten-free'],ARRAY['breakfast','brunch'],false,'$'),
('seed','bf-002','Blueberry Pancakes','American','https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=1200&q=80','Fluffy pancakes loaded with juicy blueberries.','[{"name":"flour"},{"name":"milk"},{"name":"egg"},{"name":"blueberries"}]'::jsonb,'Mix batter, fold in blueberries, cook on griddle.',ARRAY['skillet','spatula'],20,420,ARRAY['vegetarian','sweet'],ARRAY[]::text[],ARRAY['breakfast'],false,'$'),
('seed','bf-003','Eggs Benedict','American','https://images.unsplash.com/photo-1608039755401-742074f0548d?w=1200&q=80','Poached eggs with hollandaise on English muffin.','[{"name":"egg"},{"name":"english muffin"},{"name":"canadian bacon"},{"name":"hollandaise"}]'::jsonb,'Toast muffin, top with bacon, poached egg, sauce.',ARRAY['saucepan','whisk'],25,560,ARRAY['savory','brunch'],ARRAY[]::text[],ARRAY['breakfast','brunch'],false,'$$'),
('seed','bf-004','Acai Bowl','Brazilian','https://images.unsplash.com/photo-1490474504059-bf2db5ab2348?w=1200&q=80','Acai blended with banana, topped with granola and fruit.','[{"name":"acai puree"},{"name":"banana"},{"name":"granola"},{"name":"berries"}]'::jsonb,'Blend acai with banana, top with granola and fruit.',ARRAY['blender','bowl'],10,380,ARRAY['vegan','antioxidant'],ARRAY['vegan','dairy-free'],ARRAY['breakfast'],false,'$$'),
('seed','bf-005','Breakfast Burrito','Mexican','https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=1200&q=80','Tortilla wrapped around eggs, beans, cheese and salsa.','[{"name":"tortilla"},{"name":"egg"},{"name":"black beans"},{"name":"cheese"},{"name":"salsa"}]'::jsonb,'Scramble eggs, fill tortilla with beans, cheese, salsa.',ARRAY['skillet'],15,520,ARRAY['savory','filling'],ARRAY[]::text[],ARRAY['breakfast'],false,'$'),
('seed','bf-006','Avocado Smoothie Bowl','Healthy','https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=1200&q=80','Creamy avocado-banana smoothie in a bowl.','[{"name":"avocado"},{"name":"banana"},{"name":"spinach"},{"name":"almond milk"}]'::jsonb,'Blend, pour into bowl, top with seeds.',ARRAY['blender'],8,360,ARRAY['vegan','healthy'],ARRAY['vegan','gluten-free','dairy-free'],ARRAY['breakfast'],false,'$'),
('seed','bf-007','Belgian Waffles','Belgian','https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=1200&q=80','Crisp waffles with butter and maple syrup.','[{"name":"flour"},{"name":"egg"},{"name":"milk"},{"name":"butter"}]'::jsonb,'Whisk batter, cook in waffle iron.',ARRAY['waffle iron'],20,480,ARRAY['vegetarian','sweet'],ARRAY[]::text[],ARRAY['breakfast','brunch'],false,'$'),
('seed','bf-008','Smoked Salmon Bagel','Jewish-American','https://images.unsplash.com/photo-1592151450430-c2dbeebac6e9?w=1200&q=80','Bagel with cream cheese, lox, capers and red onion.','[{"name":"bagel"},{"name":"cream cheese"},{"name":"smoked salmon"},{"name":"capers"}]'::jsonb,'Toast bagel, spread cheese, top with salmon and capers.',ARRAY['knife'],8,510,ARRAY['savory','high-protein'],ARRAY[]::text[],ARRAY['breakfast','brunch'],false,'$$'),
('seed','bf-009','Steel-Cut Oatmeal','American','https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=1200&q=80','Hearty oats with banana, walnuts, and cinnamon.','[{"name":"steel cut oats"},{"name":"banana"},{"name":"walnut"},{"name":"cinnamon"}]'::jsonb,'Simmer oats, top with banana and walnuts.',ARRAY['saucepan'],25,340,ARRAY['vegan','healthy','high-fiber'],ARRAY['vegan','gluten-free'],ARRAY['breakfast'],false,'$'),
('seed','bf-010','Chia Pudding','Healthy','https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=1200&q=80','Chia seeds set in coconut milk with fresh fruit.','[{"name":"chia seeds"},{"name":"coconut milk"},{"name":"mango"}]'::jsonb,'Mix chia and milk, refrigerate, top with fruit.',ARRAY['jar','spoon'],5,290,ARRAY['vegan','no-cook'],ARRAY['vegan','gluten-free','dairy-free'],ARRAY['breakfast'],false,'$'),
('seed','bf-011','Huevos Rancheros','Mexican','https://images.unsplash.com/photo-1565895405127-481853366cf8?w=1200&q=80','Fried eggs over tortillas with ranchero salsa.','[{"name":"egg"},{"name":"corn tortilla"},{"name":"tomato salsa"},{"name":"black beans"}]'::jsonb,'Warm tortillas, top with eggs, beans, and salsa.',ARRAY['skillet'],20,460,ARRAY['savory','spicy'],ARRAY['gluten-free'],ARRAY['breakfast','brunch'],false,'$'),
('seed','bf-012','Croissant & Jam','French','https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=1200&q=80','Buttery croissant with strawberry jam.','[{"name":"croissant"},{"name":"butter"},{"name":"strawberry jam"}]'::jsonb,'Warm croissant, serve with jam and butter.',ARRAY['oven'],10,380,ARRAY['vegetarian','sweet'],ARRAY[]::text[],ARRAY['breakfast'],false,'$'),
('seed','bf-013','Breakfast Sausage Hash','American','https://images.unsplash.com/photo-1529042410759-befb1204b468?w=1200&q=80','Crispy potatoes with sausage, peppers, and eggs.','[{"name":"potato"},{"name":"sausage"},{"name":"bell pepper"},{"name":"egg"}]'::jsonb,'Crisp potatoes, add sausage and peppers, top with egg.',ARRAY['cast iron'],30,620,ARRAY['savory','hearty'],ARRAY['gluten-free'],ARRAY['breakfast','brunch'],false,'$'),
('seed','bf-014','Banana Bread','American','https://images.unsplash.com/photo-1605286658776-0a3a8b8c8b8b?w=1200&q=80','Moist banana loaf with walnuts.','[{"name":"banana"},{"name":"flour"},{"name":"sugar"},{"name":"walnut"}]'::jsonb,'Mix and bake at 350F for 60 minutes.',ARRAY['loaf pan','oven'],75,310,ARRAY['vegetarian','sweet'],ARRAY[]::text[],ARRAY['breakfast','snack'],false,'$'),
('seed','bf-015','Veggie Frittata','Italian','https://images.unsplash.com/photo-1623428454603-3e0d3e8f8f8f?w=1200&q=80','Open-faced omelette with spinach, tomato, and feta.','[{"name":"egg"},{"name":"spinach"},{"name":"tomato"},{"name":"feta"}]'::jsonb,'Whisk eggs with veggies, bake until set.',ARRAY['oven-safe skillet','oven'],25,380,ARRAY['vegetarian','high-protein'],ARRAY['gluten-free'],ARRAY['breakfast','brunch'],false,'$$'),
('seed','bf-016','English Breakfast','British','https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=1200&q=80','Eggs, bacon, sausage, beans, tomato, and toast.','[{"name":"egg"},{"name":"bacon"},{"name":"sausage"},{"name":"baked beans"},{"name":"tomato"},{"name":"toast"}]'::jsonb,'Cook each component, plate together.',ARRAY['skillet'],30,820,ARRAY['savory','hearty'],ARRAY[]::text[],ARRAY['breakfast'],false,'$$'),

-- ============ LUNCH (need ~6 more) ============
('seed','lu-001','Margherita Flatbread','Italian','https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=1200&q=80','Crispy flatbread with tomato, mozzarella, and basil.','[{"name":"flatbread"},{"name":"tomato"},{"name":"mozzarella"},{"name":"basil"}]'::jsonb,'Top flatbread and bake at 450F until bubbly.',ARRAY['oven','tray'],15,520,ARRAY['vegetarian'],ARRAY[]::text[],ARRAY['lunch'],false,'$'),
('seed','lu-002','Cobb Salad','American','https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=1200&q=80','Loaded salad with chicken, bacon, egg, avocado, blue cheese.','[{"name":"romaine"},{"name":"chicken"},{"name":"bacon"},{"name":"egg"},{"name":"avocado"},{"name":"blue cheese"}]'::jsonb,'Arrange ingredients in rows on lettuce, drizzle dressing.',ARRAY['knife','bowl'],20,580,ARRAY['high-protein'],ARRAY['gluten-free'],ARRAY['lunch'],false,'$$'),
('seed','lu-003','Tuna Poke Bowl','Hawaiian','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&q=80','Cubed ahi tuna over rice with avocado and edamame.','[{"name":"ahi tuna"},{"name":"sushi rice"},{"name":"avocado"},{"name":"edamame"},{"name":"soy sauce"}]'::jsonb,'Marinate tuna, build bowl over rice.',ARRAY['knife','bowl'],20,540,ARRAY['high-protein','fresh'],ARRAY['dairy-free'],ARRAY['lunch','dinner'],false,'$$'),
('seed','lu-004','Turkey Club Sandwich','American','https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=1200&q=80','Triple-decker with turkey, bacon, lettuce, tomato.','[{"name":"bread"},{"name":"turkey"},{"name":"bacon"},{"name":"lettuce"},{"name":"tomato"}]'::jsonb,'Toast bread, layer fillings, slice in quarters.',ARRAY['toaster','knife'],10,650,ARRAY['classic'],ARRAY[]::text[],ARRAY['lunch'],false,'$'),
('seed','lu-005','Ramen Bowl Veggie','Japanese','https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=1200&q=80','Vegetarian miso ramen with tofu and bok choy.','[{"name":"ramen noodles"},{"name":"miso"},{"name":"tofu"},{"name":"bok choy"},{"name":"egg"}]'::jsonb,'Simmer broth, cook noodles, assemble bowl.',ARRAY['stockpot','ladle'],30,560,ARRAY['vegetarian','umami'],ARRAY[]::text[],ARRAY['lunch','dinner'],false,'$'),
('seed','lu-006','Chicken Burrito Bowl','Mexican','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=1200&q=80','Grilled chicken over rice with beans, salsa, guacamole.','[{"name":"chicken"},{"name":"rice"},{"name":"black beans"},{"name":"guacamole"},{"name":"salsa"}]'::jsonb,'Grill chicken, build bowl with toppings.',ARRAY['grill pan','bowl'],25,680,ARRAY['high-protein'],ARRAY['gluten-free'],ARRAY['lunch','dinner'],false,'$'),
('seed','lu-007','Lentil Soup','Mediterranean','https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=80','Hearty red lentil soup with carrots and cumin.','[{"name":"red lentils"},{"name":"carrot"},{"name":"onion"},{"name":"cumin"}]'::jsonb,'Simmer lentils with veggies until tender, blend partially.',ARRAY['pot','blender'],40,320,ARRAY['vegan','high-fiber'],ARRAY['vegan','gluten-free','dairy-free'],ARRAY['lunch','dinner'],false,'$'),

-- ============ DINNER (already 22, but add a few correctly-imaged extras) ============
('seed','di-001','Honey Garlic Glazed Salmon','American','https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1200&q=80','Pan-seared salmon glazed with honey and garlic.','[{"name":"salmon"},{"name":"honey"},{"name":"garlic"},{"name":"soy sauce"}]'::jsonb,'Sear salmon, glaze with honey-garlic-soy sauce.',ARRAY['skillet'],20,520,ARRAY['high-protein','quick'],ARRAY['dairy-free'],ARRAY['dinner'],false,'$$'),
('seed','di-002','BBQ Pulled Chicken','American','https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=1200&q=80','Slow-cooked chicken with smoky BBQ sauce.','[{"name":"chicken thighs"},{"name":"bbq sauce"},{"name":"onion"}]'::jsonb,'Slow cook chicken in BBQ sauce, shred.',ARRAY['slow cooker','forks'],240,540,ARRAY['comfort','smoky'],ARRAY['dairy-free'],ARRAY['dinner'],false,'$'),
('seed','di-003','Cauliflower Steak','Vegan','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&q=80','Roasted cauliflower with chimichurri.','[{"name":"cauliflower"},{"name":"olive oil"},{"name":"chimichurri"}]'::jsonb,'Slice and roast cauliflower, top with chimichurri.',ARRAY['oven','sheet pan'],35,280,ARRAY['vegan','low-carb'],ARRAY['vegan','gluten-free','dairy-free'],ARRAY['dinner'],false,'$'),

-- ============ DESSERT (need ~19 more) ============
('seed','de-001','Chocolate Lava Cake','French','https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200&q=80','Molten chocolate cake with a gooey center.','[{"name":"dark chocolate"},{"name":"butter"},{"name":"egg"},{"name":"sugar"},{"name":"flour"}]'::jsonb,'Bake at 425F for 12 minutes; serve immediately.',ARRAY['ramekin','oven'],20,480,ARRAY['dessert','chocolate'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-002','Tiramisu','Italian','https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=1200&q=80','Coffee-soaked ladyfingers with mascarpone cream.','[{"name":"ladyfingers"},{"name":"mascarpone"},{"name":"espresso"},{"name":"cocoa"}]'::jsonb,'Layer dipped ladyfingers with mascarpone cream; chill.',ARRAY['dish','whisk'],30,420,ARRAY['dessert','italian'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-003','New York Cheesecake','American','https://images.unsplash.com/photo-1567327613485-fbc7bf196198?w=1200&q=80','Dense, creamy cheesecake on a graham crust.','[{"name":"cream cheese"},{"name":"sugar"},{"name":"egg"},{"name":"graham cracker"}]'::jsonb,'Bake in water bath at 325F for 70 minutes; chill.',ARRAY['springform pan','oven'],90,520,ARRAY['dessert','classic'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-004','Crème Brûlée','French','https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=1200&q=80','Vanilla custard with a torched sugar crust.','[{"name":"cream"},{"name":"egg yolk"},{"name":"vanilla"},{"name":"sugar"}]'::jsonb,'Bake custards, chill, torch sugar tops.',ARRAY['ramekin','torch'],60,440,ARRAY['dessert','french'],ARRAY['gluten-free'],ARRAY['dessert'],false,'$$$'),
('seed','de-005','Apple Pie','American','https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=1200&q=80','Flaky pie with cinnamon-spiced apples.','[{"name":"apple"},{"name":"pie crust"},{"name":"cinnamon"},{"name":"sugar"}]'::jsonb,'Fill crust with apples; bake at 375F for 50 minutes.',ARRAY['pie pan','oven'],75,380,ARRAY['dessert','classic'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-006','Strawberry Shortcake','American','https://images.unsplash.com/photo-1488477181946-6428a0291777?w=1200&q=80','Biscuits layered with cream and strawberries.','[{"name":"biscuit"},{"name":"strawberry"},{"name":"whipped cream"}]'::jsonb,'Split biscuits, fill with cream and berries.',ARRAY['oven','whisk'],30,360,ARRAY['dessert','fruity'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-007','Brownies','American','https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200&q=80','Fudgy chocolate brownies.','[{"name":"chocolate"},{"name":"butter"},{"name":"sugar"},{"name":"egg"},{"name":"flour"}]'::jsonb,'Bake at 350F for 25 minutes.',ARRAY['oven','pan'],35,310,ARRAY['dessert','chocolate'],ARRAY[]::text[],ARRAY['dessert'],false,'$'),
('seed','de-008','Macarons','French','https://images.unsplash.com/photo-1558326567-98ae2405596b?w=1200&q=80','Delicate almond meringue cookies with ganache.','[{"name":"almond flour"},{"name":"egg white"},{"name":"powdered sugar"},{"name":"ganache"}]'::jsonb,'Pipe shells, bake, sandwich with ganache.',ARRAY['piping bag','oven'],90,180,ARRAY['dessert','french'],ARRAY['gluten-free'],ARRAY['dessert'],false,'$$$'),
('seed','de-009','Panna Cotta','Italian','https://images.unsplash.com/photo-1488477304112-4944851de03d?w=1200&q=80','Silky vanilla cream with berry coulis.','[{"name":"cream"},{"name":"sugar"},{"name":"gelatin"},{"name":"vanilla"},{"name":"berries"}]'::jsonb,'Set cream with gelatin; chill; top with coulis.',ARRAY['saucepan','ramekin'],240,320,ARRAY['dessert','italian'],ARRAY['gluten-free'],ARRAY['dessert'],false,'$$'),
('seed','de-010','Key Lime Pie','American','https://images.unsplash.com/photo-1551024601-bec78aea704b?w=1200&q=80','Tart-and-sweet lime pie on a graham crust.','[{"name":"key lime juice"},{"name":"condensed milk"},{"name":"egg yolk"},{"name":"graham crust"}]'::jsonb,'Whisk filling, bake 15 min, chill.',ARRAY['oven','pie pan'],30,400,ARRAY['dessert','citrus'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-011','Banana Cream Pie','American','https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=1200&q=80','Banana custard pie topped with whipped cream.','[{"name":"banana"},{"name":"vanilla custard"},{"name":"pie crust"},{"name":"whipped cream"}]'::jsonb,'Layer custard and bananas in crust; top with cream.',ARRAY['pie pan'],45,420,ARRAY['dessert'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-012','Cinnamon Rolls','American','https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=1200&q=80','Soft rolls with cinnamon swirl and icing.','[{"name":"flour"},{"name":"yeast"},{"name":"cinnamon"},{"name":"butter"},{"name":"icing"}]'::jsonb,'Roll dough, fill, bake, drizzle icing.',ARRAY['oven','pan'],120,420,ARRAY['dessert','breakfast'],ARRAY[]::text[],ARRAY['dessert','breakfast'],false,'$'),
('seed','de-013','Mango Sticky Rice','Thai','https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=1200&q=80','Sweet sticky rice with ripe mango and coconut.','[{"name":"sticky rice"},{"name":"coconut milk"},{"name":"mango"}]'::jsonb,'Steam rice, mix with sweet coconut milk, serve with mango.',ARRAY['steamer'],45,380,ARRAY['vegan','dessert'],ARRAY['vegan','gluten-free','dairy-free'],ARRAY['dessert'],false,'$'),
('seed','de-014','Churros','Spanish','https://images.unsplash.com/photo-1624371414361-e670edf4898d?w=1200&q=80','Fried dough sticks dusted with cinnamon sugar.','[{"name":"flour"},{"name":"butter"},{"name":"egg"},{"name":"cinnamon sugar"}]'::jsonb,'Pipe and fry dough; toss in cinnamon sugar.',ARRAY['piping bag','fryer'],30,340,ARRAY['dessert','fried'],ARRAY[]::text[],ARRAY['dessert'],false,'$'),
('seed','de-015','Pavlova','Australian','https://images.unsplash.com/photo-1488477181946-6428a0291777?w=1200&q=80','Crisp meringue topped with cream and fruit.','[{"name":"egg white"},{"name":"sugar"},{"name":"cream"},{"name":"berries"}]'::jsonb,'Bake meringue, top with whipped cream and berries.',ARRAY['oven','whisk'],90,300,ARRAY['dessert','gluten-free'],ARRAY['gluten-free'],ARRAY['dessert'],false,'$$'),
('seed','de-016','Carrot Cake','American','https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=1200&q=80','Spiced carrot cake with cream cheese frosting.','[{"name":"carrot"},{"name":"flour"},{"name":"sugar"},{"name":"cream cheese"}]'::jsonb,'Bake layers, frost with cream cheese.',ARRAY['oven','mixer'],60,460,ARRAY['dessert'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-017','Lemon Tart','French','https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=1200&q=80','Buttery shell with bright lemon curd.','[{"name":"lemon"},{"name":"egg"},{"name":"butter"},{"name":"sugar"},{"name":"tart shell"}]'::jsonb,'Bake shell, fill with lemon curd, chill.',ARRAY['tart pan','oven'],60,360,ARRAY['dessert','citrus'],ARRAY[]::text[],ARRAY['dessert'],false,'$$'),
('seed','de-018','Bread Pudding','American','https://images.unsplash.com/photo-1626078299034-94be9c8c2f25?w=1200&q=80','Custard-soaked bread baked golden, with caramel sauce.','[{"name":"bread"},{"name":"egg"},{"name":"milk"},{"name":"sugar"},{"name":"caramel"}]'::jsonb,'Soak bread in custard, bake until set.',ARRAY['oven','dish'],60,440,ARRAY['dessert','comfort'],ARRAY[]::text[],ARRAY['dessert'],false,'$'),
('seed','de-019','Affogato','Italian','https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=1200&q=80','Vanilla gelato drowned in hot espresso.','[{"name":"vanilla gelato"},{"name":"espresso"}]'::jsonb,'Scoop gelato, pour espresso over.',ARRAY['cup','espresso machine'],3,260,ARRAY['dessert','quick'],ARRAY['gluten-free'],ARRAY['dessert'],false,'$');
